#!/bin/bash

#Get disks from device with ip $2 and community $3
#and than replace disk enclosure OID with disk health OID 
DiskList=`snmpbulkwalk -v2c -c $3 -Onq -r 0 -t 1 $2 1.3.6.1.4.1.34774.4.1.23.5.1.1.4 | grep -i "$4" | cut -d" " -f1 | sed 's/1\.3\.6\.1\.4\.1\.34774\.4\.1\.23\.5\.1\.1\.4/1.3.6.1.4.1.34774.4.1.23.5.1.1.2/g' 2>/dev/null`

if [ $? -eq 0 ]
then
  #Succefully received time value or "No OID available" message
  if [[ $DiskList == No* ]]
  then
    # No such OID available.
    echo "-1"
    exit 0
  else
    NonHealthyDiskCount=`snmpbulkwalk -v2c -c $3 -Onq -r 0 -t 1 $2 1.3.6.1.4.1.34774.4.1.23.5.1.1.2 | grep -i "$DiskList" | cut -d" " -f2 | grep -v "^1$" | grep -c . 2>/dev/null`
    echo -e "$NonHealthyDiskCount" 2>/dev/null
    exit 0
  fi
else
  # Wrong community specified or smth. Cannot retrive OID value. Quitting with error.
  echo "-100500"
  exit 0
fi
