#!/bin/bash

#Get alarms from device with ip $2 and community $3
Alarms=`snmpwalk -v2c -c $3 -Oqv -r 0 -t 1 $2 .1.3.6.1.4.1.2011.2.91.10.1.1.1.4 | grep -v "Storage Pool Remaining Capacity Is Insufficient" 2>/dev/null`

if [ $? -eq 0 ]
then
  #Succefully received time value or "No OID available" message
  if [[ $Alarms == No* ]]
  then
    # No such OID available. Weird, but OceanStor returns this if there are no alarms at all.
    echo "0"
    exit 0
  else
    echo -e "$Alarms" | grep -c . 2>/dev/null
    exit 0
  fi
else
  # Wrong community specified or smth. Cannot retrive OID value. Quitting with error.
  echo "-100500"
  exit 0
fi
