#!/bin/bash
#Get BGP neighbor from device with ip $2 and community $3 
OID=".1.3.6.1.4.1.9.9.187.1.2.4.1.1"
OIDesc=`printf "%q." "$OID" 2>/dev/null`
BGPPeerAcceptedPrefixes=`snmpwalk -v2c -c $3 -Onq -r 0 -t 1 $2 $OID 2>/dev/null`

if [ $? -eq 0 ]
then
  #Succefully received time value or "No OID available" message
  if [[ $BGPPeerAcceptedPrefixes == No* ]]
  then
    # No such OID available. Device does not support NTP MIB. Quitting with no error.
    echo "-100501"
    exit 0
  else
    IFS='
'
    for BGPPrefix in $BGPPeerAcceptedPrefixes; do
      SNMPIndex=${BGPPrefix#"$OIDesc"}
      SNMPValue=`echo $SNMPIndex | cut -d' ' -f 2`
      SNMPIndex=`echo $SNMPIndex | cut -d' ' -f 1`
      SNMPDescr=`echo $SNMPIndex | cut -d'.' -f "1-4"`
      jq -n --arg SNMPIndex "$SNMPIndex" --arg SNMPDescr "$SNMPDescr" '{"{#INDEX}": $SNMPIndex, "{#VALUE}": $SNMPDescr}'
    done | jq -n '.data |= [inputs]'
    exit 0
  fi
else
  # Wrong community specified or smth. Cannot retrive OID value. Quitting with error.
  echo "-100500"
  exit 0
fi
