#!/bin/bash

# Get number of IP's used in ASA (from local IP pool) matching regex $4 from device with ip $2 community $3

IPCount=`snmpbulkwalk -v2c -c $3 -Oqvf -r 0 -t 2 $2 1.3.6.1.4.1.9.9.392.1.3.21.1.8 | grep -i "$4" | sort | uniq | wc -l 2>/dev/null`

if [ $? -eq 0 ]
then
  #Succefully received disk state or "No OID available" message
  if [[ $IPCount == No* ]]
  then
    # No such OID available - quitting with error code to mark item as unavailable
    echo "0"
    exit 1
  else
    echo "$IPCount"
    exit 0
  fi
else
  # Community is wrong, connection timeout or something else
  echo "0"
  exit 2
fi
