#!/bin/bash

Timeout=5

#Get alarms from device with ip $2 and community $3
LUNTraffic=$(snmpbulkwalk -v2c -c $3 -Oqn -r 0 -t "$Timeout" $2 1.3.6.1.4.1.34774.4.1.21.4.1.6 2>/dev/null)

if [ $? -eq 0 ]
then
  #Succefully received time value or "No OID available" message
  if [[ $LUNTraffic == No* ]]
  then
    # No such OID available.
    echo "0"
    exit 0
  else
    if [ -z $4 ]; then
      TopCount=5
    else
      TopCount="$4"
    fi
    LUNTraffic=$(echo -e "$LUNTraffic" | cut -d'.' -f15-)
    LUNIOPS=$(snmpbulkwalk -v2c -c $3 -Oqn -r 0 -t "$Timeout" $2 1.3.6.1.4.1.34774.4.1.21.4.1.3 2>/dev/null | cut -d'.' -f15-)
    LUNNAMES=$(snmpbulkwalk -v2c -c $3 -Oqn -r 0 -t "$Timeout" $2 1.3.6.1.4.1.34774.4.1.19.9.4.1.2 2>/dev/null | cut -d'.' -f16- | sed 's/\"//g')
    IFS=$'
'
    # --- Top by MBps ---
    TopLUNTraffic=$(echo -e "$LUNTraffic" | sort -k2 -n -r | head -n "$TopCount")
    echo "TOP $TopCount by MBps"
    RESULT=''
    TotalMBps=0
    TotalIOPS=0
    for LUN in $TopLUNTraffic; do
      LUNID=$(echo "$LUN" | cut -d' ' -f1)
      CurrentLUNNAME=$(echo "$LUNNAMES" | grep "^$LUNID .*" | cut -d' ' -f2)
      CurrentLUNTraffic=$(echo "$LUN" | cut -d' ' -f2)
      CurrentLUNIOPS=$(echo "$LUNIOPS" | grep "^$LUNID .*" | cut -d' ' -f2)
      let "TotalMBps += $CurrentLUNTraffic"
      let "TotalIOPS += $CurrentLUNIOPS"
      RESULT="$RESULT\n$CurrentLUNNAME  $CurrentLUNTraffic  $CurrentLUNIOPS"
    done
    RESULT="$RESULT\nSUM-top-$TopCount  $TotalMBps  $TotalIOPS"
    echo -e "$RESULT" | column --table --table-columns NAME,MBps,IOPS --table-right MBps,IOPS

    # --- Top by IOPS ---
    TopLUNIOPS=$(echo -e "$LUNIOPS" | sort -k2 -n -r | head -n "$TopCount")
    echo ""
    echo "TOP $TopCount by IOPS"
    RESULT=''
    TotalMBps=0
    TotalIOPS=0
    for LUN in $TopLUNIOPS; do
      LUNID=$(echo "$LUN" | cut -d' ' -f1)
      CurrentLUNNAME=$(echo "$LUNNAMES" | grep "^$LUNID .*" | cut -d' ' -f2)
      CurrentLUNIOPS=$(echo "$LUN" | cut -d' ' -f2)
      CurrentLUNTraffic=$(echo "$LUNTraffic" | grep "^$LUNID .*" | cut -d' ' -f2)
      let "TotalMBps += $CurrentLUNTraffic"
      let "TotalIOPS += $CurrentLUNIOPS"
      RESULT="$RESULT\n$CurrentLUNNAME  $CurrentLUNTraffic  $CurrentLUNIOPS"
    done
    RESULT="$RESULT\nSUM-top-$TopCount  $TotalMBps  $TotalIOPS"
    echo -e "$RESULT" | column --table --table-columns NAME,MBps,IOPS --table-right MBps,IOPS

    exit 0
  fi
else
  # Wrong community specified or smth. Cannot retrive OID value. Quitting with error.
  echo "-100500"
  exit 0
fi
