#!/bin/bash

#Get Alarm values from device with ip $2 and community $3
AlarmString=`snmpwalk -v2c -c $3 -Onqv -r 0 -t 0.5 $2 1.3.6.1.2.1.33.1.6.2.1.2 2>/dev/null`

if [ $? -eq 0 ]
then
  #Succefully received time value or "No OID available" message
  if [[ $AlarmString == No* ]]
  then
    # No such OID available. No OID or no alarms exist.
    echo "No Alarms or No OID available"
    exit 0
  else
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.24"/"upsAlarmTestInProgress,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.23"/"upsAlarmShutdownImminent,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.22"/"upsAlarmShutdownPending,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.21"/"upsAlarmAwaitingPower,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.20"/"upsAlarmCommunicationsLost,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.19"/"upsAlarmDiagnosticTestFailed,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.18"/"upsAlarmGeneralFault,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.17"/"upsAlarmFuseFailure,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.16"/"upsAlarmFanFailure,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.15"/"upsAlarmUpsSystemOff,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.14"/"upsAlarmUpsOutputOff,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.13"/"upsAlarmChargerFailed,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.12"/"upsAlarmUpsOffAsRequested,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.11"/"upsAlarmOutputOffAsRequested,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.10"/"upsAlarmBypassBad,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.9"/"upsAlarmOnBypass,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.8"/"upsAlarmOutputOverload,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.7"/"upsAlarmOutputBad,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.6"/"upsAlarmInputBad,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.5"/"upsAlarmTempBad,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.4"/"upsAlarmDepletedBattery,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.3"/"upsAlarmLowBattery,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.2"/"upsAlarmOnBattery,"}`
    AlarmString=`echo ${AlarmString//".1.3.6.1.2.1.33.1.6.3.1"/"upsAlarmBatteryBad,"}`
    AlarmString=`echo ${AlarmString/%,/}`
    echo -e $AlarmString
    exit 0
  fi
else
  # Wrong community specified or smth. Cannot retrive OID value. Quitting with error.
  echo "UPS not available via SNMP"
  exit 0
fi

