#!/bin/bash
#Get model from device with ip $2 and community $3
Timeout=0.3

entPhysicalContainedIn=`snmpbulkwalk -v2c -c $3 -Oqn -r 0 -t $Timeout $2 .1.3.6.1.2.1.47.1.1.1.1.4 2>/dev/null | tr -d '"'`
if [[ $entPhysicalContainedIn != 'No'* ]]; then
  ParentContainerID=`echo -e "$entPhysicalContainedIn" | grep ".*\s0$" | cut -d'.' -f14 | cut -d' ' -f 1`
  entPhysicalVendorType=`snmpget -v2c -c $3 -Oqvf -r 0 -t $Timeout $2 .1.3.6.1.2.1.47.1.1.1.1.2.$ParentContainerID 2>/dev/null | tr -d '"'`
  if [ -z "$entPhysicalVendorType" ]; then
    echo "Unknown"
    exit 0
  else
    echo "$entPhysicalVendorType"
    exit 0
  fi
else
  echo "Unknown"
  exit 0
fi

