#!/bin/bash

#Get last NQA results table index from device with ip $2 and community $3
#sorting by timestamp
NQAIndex=`snmpbulkwalk -v2c -c $3 -Oqn -r 0 -t 0.5 $2 1.3.6.1.4.1.2011.5.25.111.5.1.1.4 | sort -k2 | tail -1 | cut -d' ' -f1 | rev | cut -d'.' -f3 | rev 2>/dev/null`

if [ $? -eq 0 ]
then
  #Succefully received time value or "No OID available" message
  if [[ $NQAIndex == No* ]]
  then
    # No such OID available. Device does not support NTP MIB. Quitting with no error.
    echo "0"
    exit 0
  else
    #find results with specified index and values which are not 1-s (1 is the only value corresponding to success)
    NQAResults=`snmpbulkwalk -v2c -c $3 -Oqn -r 0 -t 0.5 $2 1.3.6.1.4.1.2011.5.25.111.5.1.1.8 | grep ".*\.$NQAIndex\.[0-9]\+\.[0-9]\+ [0-9]\+" | cut -d' ' -f2 | awk '$1>1{c++} END{print c+0}' 2>/dev/null`
    echo -e "$NQAResults"
    exit 0
  fi
else
  # Wrong community specified or smth. Cannot retrive OID value. Quitting with error.
  echo "0"
  exit 0
fi

