#!/bin/bash

NQAResults=$(snmpbulkwalk -v2c -c "$3" -Oqn -r 0 -t 0.5 "$2" 1.3.6.1.4.1.2011.5.25.111.5.1.1.8 2>/dev/null)

if [ $? -eq 0 ]
then
  #Succefully received time value or "No OID available" message
  if [[ $NQAResults == No* ]]
  then
    # No such OID available. Device does not support NTP MIB. Quitting with no error.
    jq -n '.data |= []'
    exit 0
  else
    NQACheckNamesRepeating=$(echo -e "$NQAResults" | cut -d'.' -f16- | rev | cut -d'.' -f4- | rev | sort -u)
    for NQACheckName in $NQACheckNamesRepeating
    do
      NQACheckRefinedName=''
      OLDIFS=$IFS
      IFS=.
      for NameSymbol in $NQACheckName
      do
        if [ "$NameSymbol" -gt 32 ]
        then
          Letter=$(printf '%x' "$NameSymbol" | xxd -r -p)
        else
          Letter=' '
        fi
        NQACheckRefinedName="$NQACheckRefinedName$Letter"
      done
      IFS=$OLDIFS
      NQACheckRefinedName=${NQACheckRefinedName# }
      NQACheckRefinedName=${NQACheckRefinedName% }
      jq -n --arg SNMPIndex "$NQACheckName" --arg SNMPDescr "$NQACheckRefinedName" '{"{#SNMPINDEX}": $SNMPIndex, "{#SNMPDESCR}": $SNMPDescr}'
    done | jq -n '.data |= [inputs]'
    exit 0
  fi
else
  # Wrong community specified or smth. Cannot retrive OID value. Quitting with error.
  jq -n '.data |= []'
  exit 0
fi

