#!/bin/bash

#Get time string from device with ip $2 and community $3
TimeString=`snmpget -v2c -c $3 -Oqv -r 0 -t 1 $2 1.3.6.1.4.1.2011.5.25.19.1.1.1.0 2>/dev/null`


if [ $? -eq 0 ]
then
  #Succefully received time value or "No OID available" message
  if [[ $TimeString == No* ]]
  then
    # No such OID available. Device does not support NTP MIB. Quitting with no error.
    echo "-100501"
    exit 0
  else
    # Timestamp available. Fixing weird huawei time format and checking difference
    # between time on huawei device and local time. Then skipping "-" if difference
    # is lesser than zero.
    TimeString=`echo $TimeString | tr  -d '"'` 
    YearHexString=`echo $TimeString | cut -d' ' -f 1-2 | tr -d ' '`
    YearString=$(printf "%d\n" 0x$YearHexString)
    MonthHexString=`echo $TimeString | cut -d' ' -f 3 | tr -d ' '`
    MonthString=$(printf "%d\n" 0x$MonthHexString)
    DayHexString=`echo $TimeString | cut -d' ' -f 4 | tr -d ' '`
    DayString=$(printf "%d\n" 0x$DayHexString)
    HourHexString=`echo $TimeString | cut -d' ' -f 5 | tr -d ' '`
    HourString=$(printf "%d\n" 0x$HourHexString)
    MinuteHexString=`echo $TimeString | cut -d' ' -f 6 | tr -d ' '`
    MinuteString=$(printf "%d\n" 0x$MinuteHexString)
    SecondHexString=`echo $TimeString | cut -d' ' -f 7 | tr -d ' '`
    SecondString=$(printf "%d\n" 0x$SecondHexString)
    HuaweiDate=`date -d "$YearString-$MonthString-$DayString $HourString:$MinuteString:$SecondString" +%s`
    LocalTime=`date +%s`
    Diff=`expr $LocalTime - $HuaweiDate`
    Diff=${Diff/-/}
    echo $Diff
    exit 0
  fi
else
  # Wrong community specified or smth. Cannot retrive OID value. Quitting with error.
  echo "-100500"
  exit 0
fi

