#!/bin/bash

#Get alarms from device with ip $1, user $2, authPassword $3, privPassword $4

#Exclude Cisco Intersite connection alarm
ExcludedAlarm="121303"

#First query - cleared alarms
RawAlarms=`snmpwalk -v3 -Oqn -r 0 -t 1 -u $2 -A $3 -X AES -X $4 -a SHA -l AuthNoPriv $1 .1.3.6.1.4.1.9.9.719.1.1.1.1.6 | grep -o "[0-9]*\s[0-9]*$" | cut -d" " -f1 2>/dev/null`

if [ $? -eq 0 ]
then
  #Succefully received time value or "No OID available" message
  if [[ $Alarms == No* ]]
  then
    # No such OID available. Weird, but OceanStor returns this if there are no alarms at all.
    echo "-100501"
    exit 0
  else
    #second query - alarm codes
    AlarmCodes=`snmpwalk -v3 -Oqn -r 0 -t 1 -u $2 -A $3 -X AES -X $4 -a SHA -l AuthNoPriv $1 .1.3.6.1.4.1.9.9.719.1.1.1.1.9 | grep -o "[0-9]*\s[0-9]*$" 2>/dev/null`
    Counter=0
    for R in $RawAlarms; do
      if [[ $AlarmCodes == *"$R"* ]]; then
        if [[ $ExcludedAlarm != *"$R"* ]]; then
          Counter=$((Counter+1))
	fi
      fi
    done
    echo "$Counter"
    exit 0
  fi
else
  # Wrong community specified or smth. Cannot retrive OID value. Quitting with error.
  echo "-100500"
  exit 0
fi


