#!/bin/bash

#Get ARP entries from device with ip $2 and community $3 from interface with ifIndex $4
ARPCount=`snmpwalk -v2c -c $3 -Ov $2 .1.3.6.1.2.1.4.22.1.4.$4 2>/dev/null | grep -c "dynamic"`

if [ $? -le 1 ]
then
  #Succefully received time value or "No OID available" message
  echo $ARPCount
  exit 0
else
  # Wrong community specified or smth. Cannot retrive OID value. Quitting with error.
  echo "-1"
  exit 0
fi

