#!/bin/bash

TIMEOUTSHORT=0.1
TIMEOUTLONG=0.5

OSPFNBRIP=`snmpwalk -r 0 -t $TIMEOUTLONG -v2c -c $3 -Oqnv $2 .1.3.6.1.2.1.14.10.1.1 2>/dev/null`

if [ $? -eq 0 ]
then
  #Succefully received OSPF neighbors or "No OID available" message
  if [[ $OSPFNBRIP == No* ]]
  then
    # No such OID available. Device does not support NTP MIB. Quitting with no error.
    #echo "-100501" - replaced by empty JSON object
    #echo "{}"
    jq -n '.data |= []'
    exit 0
  else

    IFS=$'
'

    ARPS=`snmpwalk -r 0 -t $TIMEOUTSHORT -v2c -c $3 -Oqn $2 .1.3.6.1.2.1.3.1.1.2 2>/dev/null`
    if [[ $ARPS == *No* ]]; then
      ARPS=`snmpwalk -r 0 -t $TIMEOUTSHORT -v2c -c $3 -Oqn $2 .1.3.6.1.2.1.4.35.1.4 2>/dev/null`
    fi
    #>&2 echo "|$ARPS|"
    IFDESCRS=`snmpwalk -r 0 -t $TIMEOUTLONG -v2c -c $3 -Oqn $2 .1.3.6.1.2.1.31.1.1.1.18 | grep -Ev "unrouted VLAN|^.* $" 2>/dev/null`
    #>&2 echo "|$IFDESCRS|"
    for OSPFNBR in $OSPFNBRIP; do
      #GREPIP=`echo "$OSPFNBR" | sed "s/\./\\\./g" 2>/dev/null`
      GREPIP=`echo "$OSPFNBR "`
      ARPSTR=`echo -e "$ARPS" | grep $GREPIP 2>/dev/null`
      IFACEID=`echo "$ARPSTR" | cut -f12 -d"."`
      IFACEDESCROID="\.1\.3\.6\.1\.2\.1\.31\.1\.1\.1\.18\.$IFACEID"
      IFACEDESCR=`echo -e "$IFDESCRS" | grep "$IFACEDESCROID\s" 2>/dev/null`
      #>&2 echo "|$GREPIP|"
      OSPFNBRNAME=`snmpget -r 0 -t $TIMEOUTSHORT -v2c -c $3 -Oqnv $OSPFNBR 1.3.6.1.2.1.1.5.0 2>/dev/null | cut -f1 -d"."`
      if [ -n "$OSPFNBRNAME" ]; then
        IP=$OSPFNBR
        Name=$OSPFNBRNAME
        Descr=`echo $IFACEDESCR | cut -f2- -d" "`
        jq -n --arg IP "$IP" --arg Name "$Name" --arg Descr "$Descr" '{"{#IP}": $IP, "{#NAME}": $Name, "{#DESCR}": $Descr}'
      fi
    done | jq -n '.data |= [inputs]'
    exit 0
  fi
else
  # Wrong community specified or smth. Cannot retrive OID value. Quitting with error.
  echo "-100500"
  exit 0
fi



