#!/bin/bash

# count crashdump files on device $2 with community $3 
Pattern=`date +%Y`
#Pattern=${Pattern%?}
Pattern="crashinfo_"$Pattern
#echo $Pattern
CrashdumpCount=`snmpwalk -v2c -c $3 -On -Ln -r 0 -t 1 $2 1.3.6.1.4.1.9.9.10.1.1.4.2.1.1.5 | grep -ic "$Pattern" 2>/dev/null`


if [ $? -eq 0 ]
then
  echo "$CrashdumpCount"
  exit 0
else
  echo "0"
  exit 0
fi


