#!/bin/bash

TMPDIR='/tmp/cisco_bgp_routes'
mkdir -p $TMPDIR

OID=".1.3.6.1.4.1.9.9.187.1.1.1.1.9.1.128.1.4.$4"
SNMPROUTES=$(snmpbulkwalk -v2c -c "$3" -Onq -r 0 -t 1 "$2" "$OID" 2>/dev/null | cut -d'.' -f33- | cut -d' ' -f1 | sed 's/\(.*\)\./\1\//')

if [ -z "$SNMPROUTES" ]
then
      echo "Cannot retrive routes from $4"
else
      SYSNAME=$(snmpget -v2c -c "$3" -Oqv -r 0 -t 1 "$2"  .1.3.6.1.2.1.1.5.0 2>/dev/null)
      FILENAME="$TMPDIR/$SYSNAME-$4"
      ROUTEDIFF=$(echo -e "$SNMPROUTES" | diff -Nc - "$FILENAME" | grep "^+ [0-9].*\|^- [0-9].*\|^.*$SYSNAME.*" 2>/dev/null)
      if [ -z "$ROUTEDIFF" ]
      then
        echo "Unchanged"
        if [[ ! -f "$FILENAME" ]];
        then
          echo "Writing $FILENAME"
          echo -e "$SNMPROUTES" > "$FILENAME"
        fi
      else
        echo -e "$SNMPROUTES" > "$FILENAME"
        #echo -e "$ROUTEDIFF" | sed 's/+ /# /' | sed 's/- /+ /' | sed 's/# /- /' | sed 's/! /+ /'
        echo -e "$ROUTEDIFF" | sed 's/+ \([0-9]\+\)/# \1/' | sed 's/- \([0-9]\+\)/+ \1/' | sed 's/# \([0-9]\+\)/- \1/' | sed 's/! /+ /'
      fi

      #echo "--- Routes ---"
      #echo -e "$SNMPROUTES"
      #echo "--- Routes diff ---"
      #echo -e "$ROUTEDIFF"
      #echo "$FILENAME"
fi

