#!/bin/bash

#Get number of DHCP bindings from device with ip $2 and community $3
Bindings=`snmpwalk -v2c -c $3 -Oqv -r 0 -t 1 $2 1.3.6.1.4.1.9.9.380.1.4.1.1.5 2>/dev/null`

if [ $? -eq 0 ]
then
  #Succefully received time value or "No OID available" message
  if [[ $Bindings == *"No"* ]]
  then
    # No such OID available. Ok.
    echo "0"
    exit 0
  else
    echo -e "$Bindings" | wc -l 2>/dev/null
    exit 0
  fi
else
  # Wrong community specified or smth. Cannot retrive OID value. Quitting with error.
  echo "-100500"
  exit 0
fi
