#!/bin/bash

#Get time string from device with ip $2 and community $3
TimeString=`snmpget -v2c -c $3 -Ov -r 0 -t 1 $2 1.3.6.1.4.1.9.9.168.1.1.10.0 2>/dev/null`

if [ $? -eq 0 ]
then
  #Succefully received time value or "No OID available" message
  if [[ $TimeString == No* ]]
  then
    # No such OID available. Device does not support NTP MIB. Quitting with no error.
    echo "0"
    exit 0
  else
    # Timestamp available. Fixing weird cisco time format and checking difference
    # between time on cisco device and local time. Then skipping "-" if difference
    # is lesser than zero.
    TimeString=${TimeString:12:11}
    TimeString=${TimeString// /}
    TimeString=$(printf "%d\n" 0x$TimeString)
    LocalTime=`date +%s`
    Diff=`expr $LocalTime + 2208988800 - $TimeString`
    Diff=${Diff/-/}
    echo $Diff
    exit 0
  fi
else
  # Wrong community specified or smth. Cannot retrive OID value. Quitting with error.
  echo "-100500"
  exit -100500
fi
