#!/bin/bash

# Get number of zones from device with ip $2 community $3 and VSAN ID $4

ZoneCount=`snmpbulkwalk -v2c -c $3 -Oqv -r 0 -t 2 $2 "1.3.6.1.4.1.9.9.294.1.1.7.1.2.$4" | wc -l 2>/dev/null`

if [ $? -eq 0 ]
then
  #Succefully received disk state or "No OID available" message
  if [[ $ZoneCount == No* ]]
  then
    # No such OID available - quitting with error code to mark item as unavailable
    echo "0"
    exit 1
  else
    echo "$ZoneCount"
    exit 0
  fi
else
  # Community is wrong, connection timeout or something else
  echo "0"
  exit 2
fi

