#!/bin/bash
#Get model from device with ip $2 and community $3
KNOWNMODEL=''
TIMEOUT=0.3

if [[ $# -eq 3 ]]
then
  SWITCH="$2"
  SNMPCOMMUNITY="$3"
else
  SWITCH="$1"
  SNMPCOMMUNITY="$2"
fi


chassisModel=$(snmpget -v2c -c "$SNMPCOMMUNITY" -Oqvf -r 0 -t "$TIMEOUT" "$SWITCH" 1.3.6.1.4.1.9.5.1.2.16.0 2>/dev/null | tr -d '"')
if [[ $chassisModel != 'No'* ]]; then
  KNOWNMODEL="$KNOWNMODEL"$'\n'"$chassisModel"
fi

entPhysicalModelName=$(snmpget -v2c -c "$SNMPCOMMUNITY" -Oqvf -r 0 -t "$TIMEOUT" "$SWITCH" .1.3.6.1.2.1.47.1.1.1.1.13.1 2>/dev/null | tr -d '"')
if [[ $entPhysicalModelName != 'No'* ]]; then
  KNOWNMODEL="$KNOWNMODEL"$'\n'"$entPhysicalModelName"
fi

entPhysicalNames=$(snmpbulkwalk -v2c -c "$SNMPCOMMUNITY" -Oqvf -r 0 -t "$TIMEOUT" "$SWITCH" .1.3.6.1.2.1.47.1.1.1.1.7 2>/dev/null | tr -d '"')
if [[ $entPhysicalNames != 'No'* ]]; then
  # fixed module switches
  entPhysicalName=$(echo -e "$entPhysicalNames" | grep -i 'switch .* fixed module.*' | cut -d' ' -f4)
  if [[ $entPhysicalName != 'No'* ]]; then
    KNOWNMODEL="$KNOWNMODEL"$'\n'"$entPhysicalName"
  fi

  # Nexus switches
  entPhysicalName=$(echo -e "$entPhysicalNames" | grep -i 'Nexus.* chassis.*' | cut -d' ' -f1-2)
  if [[ $entPhysicalName != 'No'* ]]; then
    KNOWNMODEL="$KNOWNMODEL"$'\n'"$entPhysicalName"
  fi

  # Small business SGxxx switches
  entPhysicalName=$(echo -e "$entPhysicalNames" | grep -Ei '^SG[0-9]{3}-[0-9]{2}$')
  if [[ $entPhysicalName != 'No'* ]]; then
    KNOWNMODEL="$KNOWNMODEL"$'\n'"$entPhysicalName"
  fi
fi

KNOWNMODEL=$(echo -e "$KNOWNMODEL" | sort -u | grep "\S" | tr '\n' ' ')
KNOWNMODEL=${KNOWNMODEL# }
KNOWNMODEL=${KNOWNMODEL% }

if [ -z "$KNOWNMODEL" ]; then
  echo "Unknown"
  exit 0
else
  echo "$KNOWNMODEL"
  exit 0
fi
