#!/bin/bash
#Get model from device with ip $2 and community $3
KnownModel=''
Timeout=0.3

chassisModel=`snmpget -v2c -c $3 -Oqvf -r 0 -t $Timeout $2 1.3.6.1.4.1.9.5.1.2.16.0 2>/dev/null | tr -d '"'`
if [[ $chassisModel != 'No'* ]]; then
  KnownModel="$KnownModel"$'\n'"$chassisModel"
fi

entPhysicalModelName=`snmpget -v2c -c $3 -Oqvf -r 0 -t $Timeout $2 .1.3.6.1.2.1.47.1.1.1.1.13.1 2>/dev/null | tr -d '"'`
if [[ $entPhysicalModelName != 'No'* ]]; then
  KnownModel="$KnownModel"$'\n'"$entPhysicalModelName"
fi

entPhysicalNames=`snmpbulkwalk -v2c -c $3 -Oqvf -r 0 -t $Timeout $2 .1.3.6.1.2.1.47.1.1.1.1.7 2>/dev/null | tr -d '"'`
if [[ $entPhysicalNames != 'No'* ]]; then
  entPhysicalName=`echo -e "$entPhysicalNames" | grep -i 'switch .* fixed module.*' | cut -d' ' -f4`
  if [[ $entPhysicalName != 'No'* ]]; then
    KnownModel="$KnownModel"$'\n'"$entPhysicalName"
  fi

  entPhysicalName=`echo -e "$entPhysicalNames" | grep -i 'Nexus.* chassis.*' | cut -d' ' -f1-2`
  if [[ $entPhysicalName != 'No'* ]]; then
    KnownModel="$KnownModel"$'\n'"$entPhysicalName"
  fi
fi

KnownModel=`echo -e "$KnownModel" | sort -u | grep "\S" | tr '\n' ' '`
KnownModel=${KnownModel# }
KnownModel=${KnownModel% }

if [ -z "$KnownModel" ]; then
  echo "Unknown"
else
  echo "$KnownModel"
fi
