#!/bin/bash

TIMEOUTLONG=1.5

# Get number of flogi on interface with SNMPINDEX $4 from device with ip $2 community $3
# four arguments version (which skips the first argument) left to save the compatibility with old templates
if [[ $# -eq 4 ]]
then
  FCSWITCH="$2"
  SNMPCOMMUNITY="$3"
  FCPORTID="$4" 
else
  FCSWITCH="$1"
  SNMPCOMMUNITY="$2"
  FCPORTID="$3"
fi

if [[ -z $FCPORTID ]] || [[ $FCPORTID == 'all' ]]
then
  OID='.1.3.6.1.4.1.9.9.289.1.1.5.1.3'
else
  OID=".1.3.6.1.4.1.9.9.289.1.1.5.1.3.$FCPORTID"	
fi

if FLOGI=$(snmpbulkwalk -v2c -c "$SNMPCOMMUNITY" -Oqv -r 0 -t "$TIMEOUTLONG" "$FCSWITCH" "$OID" 2>/dev/null)
then
  #Succefully received FLOGI WWNs count or "No OID available" message
  if [[ $FLOGI == No* ]]
  then
    # No such OID available - Ok. Means there is no flogi on port - return 0.
    echo "0"
    exit 0
  else
    echo -e "$FLOGI" | grep -c . 2>/dev/null
#    echo "$FLOGI"
    exit 0
  fi
else
  # Community is wrong, connection timeout or something else
  echo "-2"
  exit 2
fi

