#!/bin/bash

#Get time string from device with ip $2 and community $3
TimeString=`snmpget -v2c -c $3 -Oqv -r 0 -t 1 $2 1.3.6.1.4.1.9.9.168.1.1.10.0 2>/dev/null`


if [ $? -eq 0 ]
then
  #Succefully received time value or "No OID available" message
  if [[ $TimeString == No* ]]
  then
    # No such OID available. Device does not support NTP MIB. Quitting with no error.
    echo "-100501"
    exit 0
  else

    TimeString=`echo $TimeString | tr  -d '"' | tr  -d '[:space:]' | head -c 8 2>/dev/null`
    TimeString=`echo $((16#$TimeString)) 2>/dev/null`

    LocalTime=`date +%s`
    Diff=`expr $LocalTime + 2208988800 - $TimeString`
    Diff=${Diff/-/}
    echo $Diff
    exit 0
  fi
else
  # Wrong community specified or smth. Cannot retrive OID value. Quitting with error.
  echo "-100500"
  exit 0
fi


