#!/bin/bash

TIMEOUTLONG=0.5

#Get ospf neighbour (with IP $4) state from device with ip $2 and community $3
nbrState=`snmpget -v2c -c $3 -Oqev -m -OSPF-MIB -r 0 -t $TIMEOUTLONG $2 .1.3.6.1.2.1.14.10.1.6.$4.0 2>/dev/null`

if [ $? -eq 0 ]
then
  #Succefully received time value or "No OID available" message
  if [[ $nbrState == No* ]]
  then
    # No such OID available. No OSPF neighbour with specified IP exist
    # Zero value seems to be good, cause it is lower then Down value of 1.
    echo "0"
    exit 0
  else
    echo $nbrState
    exit 0
  fi
else
  # Wrong community specified or another fail. Cannot retrive OID value.
  # Quitting with error value, and error code (zabbix item will become unsupported).
  echo -1
  exit -1
fi

